### ISSUE TITLE
Support transformers-0.6

### ISSUE THREAD

**Issue by andreasabel** [ekmett/free#215]
Please support `transfomers-0.6`.  
Atm, attempting to constrain to it gives these compilation errors:
```
Building library for free-5.1.7.. 
...
[ 9 of 20] Compiling Control.Monad.Free.Class ( src/Control/Monad/Free/Class.hs, dist/build/Control/Monad/Free/Class.o, dist/build/Control/Monad/Free/Class.dyn_o )

src/Control/Monad/Free/Class.hs:44:1: error:
    Could not load module ‘Control.Monad.Trans.List’ 

src/Control/Monad/Free/Class.hs:45:1: error:
    Could not load module ‘Control.Monad.Trans.Error’ 
```

**Comment by RyanGlScott** [comment]
At the moment, this is waiting on a new release of `mtl` that supports `transformers-0.6`. Since it appears that a new `mtl` release may be happening soon, I'll wait to see how that shakes out. In the meantime, I have an experimental [`mtl-2.3`](https://github.com/ekmett/free/tree/mtl-2.3) branch that will likely serve your needs in the interim.

**Comment by emilypi** [comment]
Just to bump this, `mtl-2.3` has been released, and `free` looks good to go to bump the dep: 

```
  -- GHC-7.8 bundles transformers-0.3,
  -- mtl-2.2.* requires transformers >=0.4
  -- mtl-2.3.* requires base >=4.12
  if impl(ghc >=7.10)
    build-depends:
      mtl               >= 2.2.2 && < 2.4
 ```

**Comment by RyanGlScott** [comment]
Thanks! I've uploaded [`free-5.1.8`](https://hackage.haskell.org/package/free-5.1.8) to Hackage with a fix.
